Repository BOA-with-elephant/Header-Frontend, pull requests merged in 2025-07, with the labels that each got.

#11 [FIX] #8 공통 CRUD 메시지 템플릿 및 도메인별 특화 메시지 리팩토링
  src/constants/messages.js
Labels: enhancement

#23 [FEATURE] #15 bossreservation check reservation list by resvDate, userName, menuName
  public/images/reservation/Close.png
  public/images/reservation/Magnifier.png
  public/images/reservation/Sort Down.png
  public/images/reservation/search_icon.png
  src/app/myshop/reservation/components/ReservationCalendar.js
  src/app/myshop/reservation/components/SearchResultList.js
  src/app/myshop/reservation/page.js
  src/styles/admin/reservation/Calendar.module.css
  src/styles/admin/reservation/ReservationManagement.module.css
  src/styles/admin/reservation/SearchResultList.module.css
Labels: enhancement

#25 [Hotfix]
  src/app/auth/signup/page.js
  src/app/page.js
Labels: enhancement

#29 [FEATURE] #27 Check Detail Reservation Modal and Create Menu Modal
  public/images/reservation/whiteCloseBtn.png
  src/app/myshop/reservation/components/DetailReservationModal.js
  src/app/myshop/reservation/components/ReservationCalendar.js
  src/app/myshop/reservation/components/ReservationMenuModal.js
  src/app/myshop/reservation/components/SearchResultList.js
  src/app/myshop/reservation/page.js
  src/styles/admin/reservation/DetailReservationModal.module.css
  src/styles/admin/reservation/ReservationMenuModal.module.css
  src/styles/admin/reservation/SearchResultList.module.css
Labels: enhancement

#31 [FEATURE] #10 UserReservation(/shops/reservation) Shop 검색 및 예약 (/shops) 프론트 구현
  package-lock.json
  package.json
  src/app/shops/components/Accordion.js
  src/app/shops/components/BookingFormPanel.js
  src/app/shops/components/KakaoMap.js
  src/app/shops/components/ShopAlertModal.js
  src/app/shops/components/ShopDetailPanel.js
  src/app/shops/components/ShopListPanel.js
  src/app/shops/page.js
  src/app/shops/reservation/components/ReservationDetail.js
  src/app/shops/reservation/components/ReservationList.js
  src/app/shops/reservation/page.js
  src/app/shops/reservation/util/dateUtils.js
  src/app/shops/util/useInfiniteScroll.js
  src/app/shops/util/useUserLocation.js
  src/styles/user/shops/ReservationPage.css
  src/styles/user/shops/ShopFinder.css
Labels: enhancement

#32 [FEATURE] #21 메세지 관리 페이지 퍼블리싱
  src/app/myshop/message/auto-setting/page.js
  src/app/myshop/message/list/page.js
  src/app/myshop/message/page.js
  src/app/myshop/message/template-setting/page.js
  src/components/layout/SideMenuBar.jsx
  src/components/message/MessageCompose.js
  src/components/message/MessageSteps.js
  src/components/message/MessageTypeSelection.js
  src/components/message/RecipientSelection.js
  src/components/message/SendOptions.js
  src/components/message/TemplateSelection.js
  src/styles/admin/message/Message.module.css
  src/styles/admin/message/MessageCompose.module.css
  src/styles/admin/message/MessageSteps.module.css
  src/styles/admin/message/MessageTypeSelection.module.css
  src/styles/admin/message/RecipientSelection.module.css
  src/styles/admin/message/SendOptions.module.css
  src/styles/admin/message/TemplateSelection.module.css
Labels: enhancement

#39 [FEATURE] #36 feature 새 메세지 작성 api 연결
  src/app/myshop/message/page.js
  src/components/message/MessageCompose.js
  src/components/message/RecipientSelection.js
  src/components/message/TemplateSelection.js
  src/styles/admin/message/TemplateSelection.module.css
Labels: enhancement

#41 [FEATURE] #28 매출 통계 페이지 전체 구현
  package-lock.json
  package.json
  src/app/myshop/sales/analytics/page.js
  src/app/myshop/sales/statistics/page.js
  src/components/layout/SideMenuBar.jsx
  src/components/sales/statistics/DetailedAnalysisTable.jsx
  src/components/sales/statistics/InsightsSection.jsx
  src/components/sales/statistics/PeriodFilter.jsx
  src/components/sales/statistics/SalesStatisticsHeader.jsx
  src/components/sales/statistics/SummaryStatsCards.jsx
  src/components/sales/statistics/charts/CategoryStatsChart.jsx
  src/components/sales/statistics/charts/MonthlyTrendChart.jsx
  src/components/sales/statistics/charts/PaymentMethodChart.jsx
  src/components/sales/statistics/charts/StatusStatsChart.jsx
  src/components/sales/statistics/charts/TransactionTrendChart.jsx
  src/components/sales/statistics/common/ChartFilter.jsx
  src/components/sales/statistics/common/Icons.jsx
  src/components/sales/statistics/common/StatsCard.jsx
  src/components/sales/statistics/index.js
  src/constants/sales/chartConfig.js
  src/hooks/sales/useChartData.js
  src/hooks/sales/useDateFilter.js
  src/hooks/sales/useSalesData.js
  src/styles/admin/sales/SalesStatistics.module.css
  src/utils/sales/dataProcessing.js
  src/utils/sales/dateUtils.js
  src/utils/sales/exportUtils.js
Labels: enhancement

#45 [HOTFIX] #44 API 경로 통일: myshop → my-shops
  src/app/myshop/menu/components/AddEditMenuCategoryModal.js
  src/app/myshop/menu/components/AddEditMenuModal.js
  src/app/myshop/menu/page.js
  src/app/myshop/sales/page.js
  src/hooks/sales/useChartData.js
  src/hooks/sales/useSalesData.js
Labels: wontfix

#42 [FEATURE] #40 feature 템플릿 관리 페이지 퍼블리싱 및 api 연결
  src/app/myshop/message/templateManagement/page.js
  src/components/layout/SideMenuBar.jsx
  src/components/message/TemplateAddModal.js
  src/components/message/TemplateCard.js
  src/components/message/TemplateEditModal.js
  src/styles/admin/message/TemplateCard.module.css
  src/styles/admin/message/TemplateManagement.module.css
  src/styles/admin/message/TemplateModal.module.css
Labels: enhancement

#46 [FEATURE] #38 BossReservation Update Reservation Info
  src/app/myshop/reservation/components/DetailReservationModal.js
  src/app/myshop/reservation/components/NewReservationModal.js
  src/app/myshop/reservation/components/ReservationCalendar.js
  src/app/myshop/reservation/components/ReservationMenuModal.js
  src/app/myshop/reservation/components/UpdateReservaionInfoModal.js
  src/app/myshop/reservation/page.js
  src/styles/admin/reservation/UpdateResvInfo.module.css
Labels: enhancement

#48 [FEATURE] 사장님 Shop 관리 페이지, Shop 휴일 정보 관리 페이지 프론트엔드 구현
  package.json
  src/app/myshop/[shopCode]/holidays/components/HolidayForm.js
  src/app/myshop/[shopCode]/holidays/components/HolidayList.js
  src/app/myshop/[shopCode]/holidays/page.js
  src/app/myshop/[shopCode]/holidays/util/dateUtils.js
  src/app/myshop/page.js
  src/app/myshop/shop/component/MyShopDetailPanel.js
  src/app/myshop/shop/component/ShopForm.js
  src/app/myshop/shop/util/autoHyphen.js
  src/app/shops/components/BookingFormPanel.js
  src/app/shops/components/ShopAlertModal.js
  src/app/shops/components/ShopDetailPanel.js
  src/app/shops/components/ShopListPanel.js
  src/app/shops/reservation/components/ReservationDetail.js
  src/app/shops/reservation/page.js
  src/styles/admin/admin-shop/AdminShop.css
  src/styles/admin/admin-shop/ShopHoliday.css
Labels: enhancement

#49 [FEATURE] #47 BossReservation Soft Delete
  src/app/myshop/reservation/components/DeleteAlertModal.js
  src/app/myshop/reservation/components/DetailReservationModal.js
  src/app/myshop/reservation/components/NewReservationModal.js
  src/app/myshop/reservation/components/ReservationCalendar.js
  src/app/myshop/reservation/components/UpdateReservaionInfoModal.js
  src/app/myshop/reservation/page.js
  src/styles/admin/reservation/DetailReservationModal.module.css
Labels: enhancement

#58 [BUG] 사이드바 안보임 이슈 해결
  src/components/layout/Layout.jsx
Labels: bug

#62 [FIX] 사이드바 수정
  src/components/layout/Layout.jsx
  src/components/layout/SideMenuBar.jsx
Labels: enhancement

#64 [FEATURE] #20 feature 메세지 모달과 연동
  src/app/myshop/customer/page.js
  src/components/message/MessageSlideModal.js
  src/components/message/TemplateSelection.js
  src/hooks/useMessageModal.js
  src/styles/admin/message/MessageSlideModal.module.css
Labels: enhancement

#70 [FIX] 사이드바 메뉴에 샵 등록 및 관리 추가, 유저 정보가 불러지지 않는 오류 수정
  src/components/layout/Layout.jsx
  src/components/layout/SideMenuBar.jsx
Labels: enhancement

#71 [FEATURE] New form and delete button
  .idea/material_theme_project_new.xml
  src/app/auth/session/page.js
  src/app/auth/session/page.module.css
  src/app/auth/users/page.js
  src/app/auth/users/page.module.css
  src/components/layout/Header.jsx
  src/components/layout/SideMenuBar.jsx
Labels: enhancement

#75 [FEATURE] #66 Shop, Adminshop, User Reservation 패치 시 헤더에 인증 기능 추가
  src/app/myshop/[shopCode]/holidays/page.js
  src/app/myshop/page.js
  src/app/myshop/shop/component/ShopForm.js
  src/app/shops/components/BookingFormPanel.js
  src/app/shops/reservation/components/ReservationDetail.js
  src/app/shops/reservation/page.js
Labels: enhancement
